name: lieBleachxDot
version: '${project.version}'
main: net.liebleachxdot.LieBleachxDot
api-version: '1.16'
softdepend:
  - TAB
  - PlaceHolderAPI
author: _a_k_u_l_k_a_
description: s lyubovyoo tg@if_wannalie
